In [6]:
import numpy as np

# Define the environment matrix
env_matrix = np.array([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1, 0, -1, 100],
    [-1, -1, -1, 0, -1, -1],
    [-1, 0, 0, -1, 0, -1],
    [0, -1, -1, 0, -1, 100],
    [-1, 0, -1, -1, 0, 100]
])

# Initialize the Q-table with zeros
num_states, num_actions = env_matrix.shape
Q = np.zeros((num_states, num_actions))

# Set hyperparameters
gamma = 0.8

# Specify the number of iterations
num_iterations = int(input("Enter the number of iterations: "))

for iteration in range(num_iterations):
    # Randomly choose a state
    state = np.random.randint(0, num_states)

    # Find the non-negative Q-values for the possible actions in the current state
    possible_actions = np.where(env_matrix[state] >= 0)[0]

    # Update the Q-values for each possible action
    for action in possible_actions:
        Q[state, action] = env_matrix[state, action] + gamma * np.max(Q[action])

    # Print the updated Q-table
    print("Q-table after state", state)
    print(Q)

print("Final Q-table:")
print(Q)

Enter the number of iterations: 3
Q-table after state 2
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Q-table after state 4
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]
Q-table after state 0
[[  0.   0.   0.   0.  80.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]
Final Q-table:
[[  0.   0.   0.   0.  80.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]
